[package]
name = "livesport-display"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.8"
defmt-rtt = "0.4.1"
embassy-executor = { version = "0.5.0", flags = ["executor-thread", "executor-interrupt"]}
embassy-executor-macros = { version = "0.4.1", features = ["nightly"] }
embassy-rp = "0.1.0"
embassy-time = "0.3.1"
panic-probe = "0.3.2"
